### ISSUE TITLE
compiling on Cygwin64 error

### ISSUE THREAD

**Issue by buzzbo** [myers/id3v2#4]
I was able to compile id3lib, and now trying to compile id3v2 on cygwin64. The output is rather long, so here is [a pastebin link](http://pastebin.com/1vWdGzX9), and the last few lines below.

```
id3v2.o:id3v2.cpp:(.text+0x23cc): undefined reference to `ID3_Tag::Update(unsigned short)'
id3v2.o:id3v2.cpp:(.text+0x2460): undefined reference to `ID3_Tag::~ID3_Tag()'
id3v2.o:id3v2.cpp:(.text+0x249b): undefined reference to `ID3_Tag::~ID3_Tag()'
id3v2.o:id3v2.cpp:(.rdata$.refptr.ID3LIB_FULL_NAME[.refptr.ID3LIB_FULL_NAME]+0x0): undefined reference to `ID3LIB_FULL_NAME'
collect2: error: ld returned 1 exit status
Makefile:10: recipe for target 'id3v2' failed
make: *** [id3v2] Error 1
```

**Comment by reducingsearchspace** [comment]
@buzzbo  hey buzzbo were you able your  solve problem. I m facing same problem.

**Comment by buzzbo** [comment]
No--I've been a bit busy. Also, I'm an enthusiast, not a developer. I was trying to search using the error just after ````c++ -L/usr/local/lib/  -pedantic -Wall -lz -lid3 -g -o id3v2 convert.o list.o id3v2.o genre.o```` but couldn't see much (from my 'enthusiast' eyes!).

**Comment by myers** [comment]
Sorry I can't be much help.  I don't have a windows box to try this out on.

**Comment by reducingsearchspace** [comment]
It's OK.  I m trying everything I could.  Actually earlier I was trying to
port nodeJs on Windows bug that doesn't work well so I switch to unix.

**Comment by ryobg** [comment]
FYI: I have built successfully on Cygwin 64. But I have installed from the package manager libid3-devel.
